### ISSUE TITLE
[5.2.1.0] Docker images not available at DockerHub

### ISSUE THREAD

**Issue by anachristofaro** [noironetworks/acc-provision#500]
Docker images version 5.2.2.0.0ef4718 not available at DockerHub:

acc-provision/provision/acc_provision/versions.yaml

```
...
  5.2:
    aci_containers_controller_version: 5.2.2.0.0ef4718
    aci_containers_host_version: 5.2.2.0.0ef4718
    aci_containers_operator_version: 5.2.2.0.0ef4718
    cnideploy_version: 5.2.2.0.0ef4718
    openvswitch_version: 5.2.2.0.5681a9b
    opflex_agent_version: 5.2.2.0.d2739da
    opflex_server_version: 5.2.2.0.d2739da
    gbp_version: 5.2.2.0.8ac1bd4
```
