### ISSUE TITLE
acc-provision-operator: can't set image version

### ISSUE THREAD

**Issue by camrossi** [noironetworks/acc-provision#588]
I did this configuration 

```
registry:
  image_prefix: quay.io/noiro
  aci_containers_controller_version: 5.2.3.1.1d150da
  aci_containers_host_version: 5.2.3.1.1d150da
  cnideploy_version: 5.2.3.1.1d150da
  opflex_agent_version: 5.2.3.1.1d150da
  openvswitch_version: 5.2.3.1.1d150da
  aci_containers_operator_version: 5.2.3.1.1d150da
  acc_provision_operator: 5.2.3.1.1d150da
```

All the images are set to 5.2.3.1.1d150da however   aci_containers_operator_version is still set to 6.0.0.0.179471b

```
cat cni-ocpbm |  grep quay | sort | uniq
                "image_prefix": "quay.io/noiro",
        image: quay.io/noiro/acc-provision-operator:6.0.0.0.179471b. <====
          image: quay.io/noiro/aci-containers-controller:5.2.3.1.1d150da
          image: quay.io/noiro/aci-containers-host:5.2.3.1.1d150da
      - image: quay.io/noiro/aci-containers-operator:5.2.3.1.1d150da
          image: quay.io/noiro/cnideploy:5.2.3.1.1d150da
          image: quay.io/noiro/openvswitch:5.2.3.1.1d150da
          image: quay.io/noiro/opflex:5.2.3.1.1d150da
```
