### ISSUE TITLE
Information on dnsnetworkpolicies in ACI CNI plugin

### ISSUE THREAD

**Issue by enrico2828** [noironetworks/acc-provision#819]
Hello, 
we were referred to Github by Cisco TAC with this enquiry. 

We are trying to find documentation about "dnsnetworkpolicies" and how to use it in Openshift version 4.10.
"dnsnetworkpolicies" is included in Cisco ACI CNI (acc-provision version 5.2.3.3) which we use to integrate ACI version 5.2(5c) with Openshift.

The following policy seems not to be functional
```
---
apiVersion: aci.dnsnetpol/v1beta
kind: DnsNetworkPolicy
metadata:
  name: dns-allow-google
  namespace: na-nettest-curlclient
spec:
  appliedTo:
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: na-nettest-curlclient
      podSelector:
        matchLabels:
          app: curl-extern
  egress:
    toFqdn:
      matchNames:
        - "google.com"
        - "noordmolenwerf.nl"
```

Could you provide more information and documentation?

$ oc api-resources

NAME SHORTNAMES APIVERSION NAMESPACED KIND

dnsnetworkpolicies aci.dnsnetpol/v1beta true DnsNetworkPolicy
